<script lang="ts">
  import { page } from '$app/stores';
  import { applications, updateApplicationStatus } from '$lib/stores/applications';
  import { formatDate, statusMeta } from '$lib/utils/overtime';

  $: application = $applications.find((item) => item.id === $page.params.id);
</script>

<svelte:head><title>{application ? `${application.id} · Overtime Desk` : '申请不存在 · Overtime Desk'}</title></svelte:head>

<div class="mx-auto max-w-4xl px-5 py-6 sm:px-8 sm:py-10">
  <a href="/" class="inline-flex items-center gap-2 text-xs font-bold text-slate-500 transition hover:text-signal">← 返回申请总览</a>
  {#if application}
    <header class="mt-7 flex flex-wrap items-start justify-between gap-5"><div><p class="text-xs font-bold uppercase tracking-[0.22em] text-signal">Request detail / 03</p><div class="mt-2 flex flex-wrap items-center gap-3"><h1 class="text-3xl font-black tracking-[-0.04em]">{application.id}</h1><span class={`inline-flex rounded-full px-3 py-1 text-xs font-bold ${statusMeta[application.status].className}`}>{statusMeta[application.status].label}</span></div><p class="mt-2 text-sm text-slate-500">创建于 {new Date(application.createdAt).toLocaleString('zh-CN', { dateStyle: 'medium', timeStyle: 'short' })} · 更新于 {new Date(application.updatedAt).toLocaleString('zh-CN', { dateStyle: 'medium', timeStyle: 'short' })}</p></div>{#if application.status === 'draft'}<div class="flex gap-2"><a href={`/applications/new?draft=${application.id}`} class="rounded-xl border border-line bg-white px-4 py-2.5 text-xs font-bold text-ink transition hover:border-slate-300">继续编辑</a><button class="rounded-xl bg-signal px-4 py-2.5 text-xs font-bold text-white transition hover:bg-[#b9151b]" on:click={() => updateApplicationStatus(application.id, 'submit')}>提交申请</button></div>{:else if application.status === 'pending'}<div class="flex flex-wrap gap-2"><button class="rounded-xl border border-line bg-white px-4 py-2.5 text-xs font-bold text-slate-500 transition hover:bg-slate-50" on:click={() => updateApplicationStatus(application.id, 'withdraw')}>撤回</button><button class="rounded-xl border border-rose-100 bg-white px-4 py-2.5 text-xs font-bold text-signal transition hover:bg-rose-50" on:click={() => updateApplicationStatus(application.id, 'reject')}>驳回</button><button class="rounded-xl bg-ink px-4 py-2.5 text-xs font-bold text-white transition hover:bg-[#1a3659]" on:click={() => updateApplicationStatus(application.id, 'approve')}>通过申请</button></div>{/if}</header>
    <div class="mt-8 grid gap-6 lg:grid-cols-[minmax(0,1fr)_280px]"><section class="rounded-2xl border border-line bg-white shadow-sm"><div class="border-b border-line px-6 py-5"><h2 class="font-extrabold">加班信息</h2></div><div class="grid gap-x-8 gap-y-6 px-6 py-6 sm:grid-cols-2"><div><p class="text-xs text-slate-400">申请人</p><p class="mt-2 text-sm font-bold">{application.applicant}</p></div><div><p class="text-xs text-slate-400">所属部门</p><p class="mt-2 text-sm font-bold">{application.department}</p></div><div><p class="text-xs text-slate-400">加班日期</p><p class="mt-2 text-sm font-bold">{formatDate(application.date)}</p></div><div><p class="text-xs text-slate-400">加班时段</p><p class="mt-2 text-sm font-bold">{application.start} — {application.end}</p></div><div><p class="text-xs text-slate-400">加班时长</p><p class="mt-2 text-xl font-black text-signal">{application.hours}<span class="ml-1 text-xs text-slate-400">小时</span></p></div><div class="sm:col-span-2"><p class="text-xs text-slate-400">加班原因</p><p class={`mt-2 text-sm font-semibold leading-7 ${application.reason ? 'text-ink' : 'text-slate-400'}`}>{application.reason || '尚未填写，可继续编辑草稿后补充'}</p></div></div></section><section class="rounded-2xl border border-line bg-white p-6 shadow-sm"><div class="flex items-center justify-between"><h2 class="font-extrabold">流程记录</h2><span class="text-xs font-bold text-slate-300">{application.history.length} 条</span></div><div class="relative mt-6 space-y-6 before:absolute before:bottom-1 before:left-[5px] before:top-1 before:w-px before:bg-line">{#each application.history as record, index}<div class="relative pl-6"><span class={`absolute left-0 top-1.5 h-3 w-3 rounded-full border-2 border-white ring-1 ${index === application.history.length - 1 ? 'bg-signal ring-signal/30' : 'bg-slate-300 ring-slate-200'}`}></span><p class="text-xs font-bold text-ink">{record.action}</p><p class="mt-1 text-xs text-slate-500">{record.actor}</p><p class="mt-1 text-[11px] text-slate-400">{new Date(record.time).toLocaleString('zh-CN', { month: 'numeric', day: 'numeric', hour: '2-digit', minute: '2-digit' })}</p>{#if record.note}<p class="mt-2 rounded-lg bg-mist px-3 py-2 text-xs leading-5 text-slate-600">{record.note}</p>{/if}</div>{/each}{#if !application.history.length}<p class="pl-6 text-xs text-slate-400">暂未提交，暂无流程记录</p>{/if}</div></section></div>
  {:else}
    <div class="mt-20 rounded-2xl border border-line bg-white p-12 text-center shadow-sm"><p class="text-4xl">⌁</p><h1 class="mt-4 text-xl font-black">申请不存在</h1><p class="mt-2 text-sm text-slate-500">这条申请可能已被移除，或者链接已失效。</p><a href="/" class="mt-6 inline-flex rounded-xl bg-ink px-5 py-3 text-sm font-bold text-white">返回申请总览</a></div>
  {/if}
</div>
